#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Demandante;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Demandante/Index.cshtml")]
    public partial class _Views_Demandante_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Demandante_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Demandante\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<!-- Scripts-->\r\n<script");

WriteLiteral(" src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.13.0.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.5.0/angular-locale_es" +
"-es.min.js\"");

WriteLiteral("></script>\r\n\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 369), Tuple.Create("\"", 416)
, Tuple.Create(Tuple.Create("", 375), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts")
, 375), false)
, Tuple.Create(Tuple.Create(" ", 384), Tuple.Create("propios/demandanteController.js", 385), true)
);

WriteLiteral("></script>\r\n\r\n\r\n\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 440), Tuple.Create("\"", 466)
, Tuple.Create(Tuple.Create("", 447), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MyCss.css")
, 447), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n\r\n<div");

WriteLiteral(" ng-app=\"app\"");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div div");

WriteLiteral(" ng-controller=\"DemandanteController\"");

WriteLiteral(" data-ng-init=\"obtenerDatosDemandante()\"");

WriteLiteral(" class=\"row profile\"");

WriteLiteral(">\r\n        <!-- PERFIL MENU -->\r\n        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"profile-sidebar\"");

WriteLiteral(">\r\n                <!-- SIDEBAR USERPIC -->\r\n                <div");

WriteLiteral(" class=\"profile-userpic\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" data-ng-src=\"data:image/jpg;base64,{{demLoad.ImagenB64}}\"");

WriteLiteral(" data-err-src=\"images/png/avatar.png\"");

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(" />\r\n                </div>\r\n                <!-- END SIDEBAR USERPIC -->\r\n      " +
"          <!-- SIDEBAR USER TITLE -->\r\n                <div");

WriteLiteral(" class=\"profile-usertitle\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"profile-usertitle-name\"");

WriteLiteral(">\r\n                        {{demLoad.Nombre}} {{demLoad.Apellido1}}\r\n            " +
"        </div>\r\n                    <div");

WriteLiteral(" class=\"profile-usertitle-job\"");

WriteLiteral(">\r\n                        Demandante\r\n                    </div>\r\n              " +
"  </div>\r\n                <!-- END SIDEBAR USER TITLE -->\r\n                <!-- " +
"SIDEBAR BUTTONS -->\r\n                <div");

WriteLiteral(" class=\"profile-userbuttons\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

WriteLiteral(">Cerrar Sesión</button>\r\n                </div>\r\n                <!-- END SIDEBAR" +
" BUTTONS -->\r\n                <!-- SIDEBAR MENU -->\r\n                <div");

WriteLiteral(" class=\"profile-usermenu\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" ng-class=\"{\'active\' : section==1}\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" ng-click=\"mostrarMiPerfil()\"");

WriteLiteral(" ng-init=\"section = 1\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\" glyphicon glyphicon-home\"");

WriteLiteral(">\r\n                                </i>\r\n                                Mis Dato" +
"s Personales\r\n                            </a>\r\n                        </li>\r\n " +
"                       <li");

WriteLiteral(" ng-class=\"{\'active\' : ofertas==1}\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" ng-click=\"mostrarOfertas()\"");

WriteLiteral(" ng-init=\"ofertas = 0\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\" glyphicon glyphicon-ok\"");

WriteLiteral(@">
                                </i>
                                Mis Ofertas
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- END MENU -->
            </div>
        </div>
        <!-- CONTENT PANEL -->
        <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n            <!-- PERFIL SECTION -->\r\n            <div");

WriteLiteral(" class=\"profile-content\"");

WriteLiteral(" name=\"section\"");

WriteLiteral(" ng-show=\"section==1\"");

WriteLiteral(" ng-switch=\"editar\"");

WriteLiteral(" >\r\n                <div");

WriteLiteral(" id=\"botonEditar\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" ng-show=\"editar==0\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" ng-click=\"modoEditar()\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-pencil\"");

WriteLiteral("></span> Editar</button>\r\n                    <button");

WriteLiteral(" ng-show=\"editar==1\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" ng-click=\"modificarDemandante()\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></span> </button>\r\n                    <button");

WriteLiteral(" ng-show=\"editar==1\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

WriteLiteral(" ng-click=\"modoEditarDesactivado()\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral("></span> </button>\r\n                </div>\r\n                <div");

WriteLiteral(" ng-switch-when=\"0\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Nombre: {{demLoad.Nombre}}</label><br />\r\n                    <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Apellidos: {{demLoad.Apellido1}} {{demLoad.Apellido2}}</label><br />\r\n          " +
"          <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Teléfono: {{demLoad.Telefono}} </label><br />\r\n                    <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Email: {{demLoad.Email}} </label><br />\r\n                    <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Edad: {{demLoad.Edad}} </label><br />\r\n                    <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Perfil Linkedin: {{demLoad.PerfilLinkedin}} </label><br />\r\n                    " +
"<label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Nivel de estudios: {{demLoad.NivelEstudiosNombre}} </label><br />\r\n             " +
"       <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Experiencia Laboral: {{demLoad.ExperienciaLaboral}} </label><br />\r\n            " +
"    </div>\r\n\r\n                <div");

WriteLiteral(" ng-switch-when=\"1\"");

WriteLiteral(">\r\n                    <span>Nombre: </span> \r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(" ng-model=\"demLoadEditar.Nombre\"");

WriteLiteral(" ng-disabled=\"\"");

WriteLiteral("/><br />\r\n                    <span>Apellidos: </span>\r\n                    <inpu" +
"t");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(" ng-model=\"demLoadEditar.Apellido1\"");

WriteLiteral(" ng-disabled=\"\"");

WriteLiteral(" />\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(" ng-model=\"demLoadEditar.Apellido2\"");

WriteLiteral(" /><br />\r\n                    <span>Teléfono: </span>\r\n                    <inpu" +
"t");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(" ng-model=\"demLoadEditar.Telefono\"");

WriteLiteral(" /><br />\r\n                    <span>Email: </span>\r\n                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(" ng-model=\"demLoadEditar.Email\"");

WriteLiteral(" /><br />\r\n                    <span>Edad: </span>\r\n                    <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(" ng-model=\"demLoadEditar.Edad\"");

WriteLiteral(" /><br />\r\n                    <span>Perfil Linkedin: </span>\r\n                  " +
"  <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(" ng-model=\"demLoadEditar.PerfilLinkedin\"");

WriteLiteral(" /><br />\r\n                    <span>Nivel de estudios: </span>\r\n                " +
"    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(" ng-model=\"demLoadEditar.NivelEstudios\"");

WriteLiteral(" /><br />\r\n                    <span>Experiencia Laboral: </span>\r\n              " +
"      <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(" ng-model=\"demLoadEditar.ExperienciaLaboral\"");

WriteLiteral(" /><br />\r\n\r\n\r\n                </div>\r\n\r\n            </div>\r\n            <!-- OFE" +
"RTAS SECTION -->\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" name=\"ofertas\"");

WriteLiteral(" ng-show=\"ofertas==1\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav nav-pills nav-justified well well-sm\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(" style=\"\"");

WriteLiteral("><a");

WriteLiteral(" data-toggle=\"pill\"");

WriteLiteral(" href=\"#misdatos\"");

WriteLiteral(">Disponibles</a></li>\r\n                    <li><a");

WriteLiteral(" data-toggle=\"pill\"");

WriteLiteral(" href=\"#misOfertas\"");

WriteLiteral(">Mis ofertas</a></li>\r\n                </ul>\r\n                <div");

WriteLiteral(" class=\"tab-content well well-sm\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"misdatos\"");

WriteLiteral(" class=\"tab-pane fade in active\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral("  id=\"table\"");

WriteLiteral(" class=\"table-striped\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral(" ");

WriteLiteral(@">
                            <thead>
                                <tr>
                                    <th>Título</th>
                                    <th >Nº Vacantes</th>
                                    <th>Fecha Inicio</th>
                                    <th>Fecha Fin</th>
                                    <th>Ver Oferta</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr");

WriteLiteral(" ng-repeat=\"oferta in listOfertas\"");

WriteLiteral(@">
                                    <td>{{oferta.Titulo}}</td>
                                    <td>{{oferta.NumeroVacantes}}</td>
                                    <td>{{oferta.FechaLanzamientoS}}</td>
                                    <td>{{oferta.FechaFinS}}</td>
                                    <td");

WriteLiteral(" class=\"tdButton\"");

WriteLiteral(">\r\n                                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#modalPageOferta\"");

WriteLiteral(" ng-click=\"verOferta(oferta)\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-eye-open\"");

WriteLiteral("></span> </button>\r\n                                    </td>\r\n                  " +
"              </tr>\r\n                            </tbody>\r\n                     " +
"   </table>\r\n                        <!--  VER OFERTA MODAL -->\r\n               " +
"         <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalPageOferta\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"exampleModalCenterTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"modal-dialog modal-dialog-centered\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"modal-header plus\"");

WriteLiteral(">\r\n                                        <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"exampleModalLongTitle\"");

WriteLiteral(" style=\"font-size: 18px;\"");

WriteLiteral(">{{ofer.Titulo}}</h5>\r\n                                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close ver\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\r\n                                        </button>\r\n             " +
"                       </div>\r\n\r\n                                    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                                    <b>Título:</b><br />\r\n    " +
"                                                <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"tituloL\"");

WriteLiteral(" id=\"tituloL\"");

WriteLiteral(">{{ofer.Titulo}}</label>\r\n                                                </div>\r" +
"\n\r\n                                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                                    <b>Fecha Fin:</b> <br />\r\n" +
"                                                    <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"fechafinL\"");

WriteLiteral(" id=\"fechafinL\"");

WriteLiteral(" />{{ofer.FechaFinS}}</label>\r\n                                                </" +
"div>\r\n\r\n                                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                                    <b>Observaciones:</b><br /" +
">\r\n                                                    <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"observL\"");

WriteLiteral(" id=\"observL\"");

WriteLiteral(" />{{ofer.Observaciones}}</label>\r\n                                              " +
"  </div>\r\n\r\n                                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                                            <b>Nº vacantes:</b" +
"><br />\r\n                                                            <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"vacantesL\"");

WriteLiteral(" id=\"vacantesL\"");

WriteLiteral(" />{{ofer.NumeroVacantes}}</label>\r\n                                             " +
"           </div>\r\n                                                        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                                            <b>Sueldo:</b><br " +
"/>\r\n                                                            <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"precioL\"");

WriteLiteral(" id=\"precioL\"");

WriteLiteral(@" />{{ofer.Sueldo}}</label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                                    <b>Descripción:</b><br />\r" +
"\n                                                    <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"descripL\"");

WriteLiteral(" id=\"descripL\"");

WriteLiteral(">{{ofer.Descripcion}}</label>\r\n                                                </" +
"div>\r\n                                            </div>\r\n                      " +
"                  </div>\r\n                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"form-group cv\"");

WriteLiteral(">\r\n                                                    <b>CV:</b><br />\r\n        " +
"                                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.CV\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"CV\"");

WriteLiteral(" id=\"CV\"");

WriteLiteral(" />\r\n                                                    <span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(" ng-show=\"userForm.CV.$error.required && (userForm.CV.$dirty && userForm.CV.$touc" +
"hed)\"");

WriteLiteral("></span>\r\n                                                </div>\r\n\r\n             " +
"                                   <div");

WriteLiteral(" class=\"form-group notas\"");

WriteLiteral(">\r\n                                                    <b>Notas:</b><br />\r\n     " +
"                                               <textarea");

WriteLiteral(" class=\"form-control notas\"");

WriteLiteral(" rows=\"1\"");

WriteLiteral(" ng-model=\"inscripcion.Notas\"");

WriteLiteral(" name=\"Notas\"");

WriteLiteral(" id=\"Notas\"");

WriteLiteral(" required></textarea>\r\n                                                    <span");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(" ng-show=\"userForm.Notas.$error.required && (userForm.Notas.$dirty && userForm.No" +
"tas.$touched)\"");

WriteLiteral("></span>\r\n                                                </div>\r\n               " +
"                                 <hr />\r\n                                       " +
"         <div");

WriteLiteral(" class=\"buttonInsc\"");

WriteLiteral(">\r\n                                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#modalPageOferta\"");

WriteLiteral(" ng-click=\"inscribirseOferta(ofer)\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-pencil\"");

WriteLiteral(@"></span> Inscribirse</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <!-- FIN VER OFERTA -->
                    </div>
                    <div");

WriteLiteral(" id=\"misOfertas\"");

WriteLiteral(" class=\"tab-pane fade in\"");

WriteLiteral(">\r\n                        <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(@">
                            <thead>
                                <tr>
                                    <th>Título</th>
                                    <th>Fecha Inicio</th>
                                    <th>Fecha Fin</th>
                                    <th>Estado</th>
                                    <th>Empresa</th>
                                    <th>Ver Oferta</th>
                                    <th>Anular inscripción</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr");

WriteLiteral(" ng-repeat=\"ofertaD in listOfertasDemandante\"");

WriteLiteral(@">
                                    <td>{{ofertaD.Titulo}}</td>
                                    <td>{{ofertaD.FechaLanzamientoS}}</td>
                                    <td>{{ofertaD.FechaFinS}}</td>
                                    <td>{{ofertaD.Nombre}}</td>
                                    <td>{{ofertaD.NombreEmpresa}}</td>
                                    <td");

WriteLiteral(" class=\"tdButton\"");

WriteLiteral(">\r\n                                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" data-toggle=\"modalD\"");

WriteLiteral(" data-target=\"#modalPageOferta\"");

WriteLiteral(" ng-click=\"verOfertaD(ofertaD)\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-eye-open\"");

WriteLiteral("></span> </button>\r\n                                    </td>\r\n                  " +
"                  <td");

WriteLiteral(" class=\"tdButton\"");

WriteLiteral(">\r\n                                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#modalPageOferta\"");

WriteLiteral(" ng-click=\"anularInscripcion(ofertaD)\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral(@"></span> </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <!------------------------------------------------------------------------------------------------------------------------------------------------>
                        <!--  VER OFERTA MODAL -->

                        <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalPageOfertaD\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"exampleModalCenterTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"modal-dialog modal-dialog-centered\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"modal-header plus\"");

WriteLiteral(">\r\n                                        <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"exampleModalLongTitle\"");

WriteLiteral(" style=\"font-size: 18px;\"");

WriteLiteral(">{{ofer.Titulo}}</h5>\r\n                                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close ver\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\r\n                                            <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\r\n                                        </button>\r\n             " +
"                       </div>\r\n\r\n                                    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                                    <b>Título:</b><br />\r\n    " +
"                                                <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"tituloL\"");

WriteLiteral(" id=\"tituloL\"");

WriteLiteral(">{{ofer.Titulo}}</label>\r\n                                                </div>\r" +
"\n\r\n                                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                                    <b>Fecha Fin:</b> <br />\r\n" +
"                                                    <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"fechafinL\"");

WriteLiteral(" id=\"fechafinL\"");

WriteLiteral(" />{{ofer.FechaFinS}}</label>\r\n                                                </" +
"div>\r\n\r\n                                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                                    <b>Observaciones:</b><br /" +
">\r\n                                                    <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"observL\"");

WriteLiteral(" id=\"observL\"");

WriteLiteral(" />{{ofer.Observaciones}}</label>\r\n                                              " +
"  </div>\r\n\r\n                                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                                            <b>Nº vacantes:</b" +
"><br />\r\n                                                            <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"vacantesL\"");

WriteLiteral(" id=\"vacantesL\"");

WriteLiteral(" />{{ofer.NumeroVacantes}}</label>\r\n                                             " +
"           </div>\r\n                                                        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                                            <b>Sueldo:</b><br " +
"/>\r\n                                                            <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"precioL\"");

WriteLiteral(" id=\"precioL\"");

WriteLiteral(@" />{{ofer.Sueldo}}</label>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                                    <b>Descripción:</b><br />\r" +
"\n                                                    <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"descripL\"");

WriteLiteral(" id=\"descripL\"");

WriteLiteral(@">{{ofer.Descripcion}}</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<br>
");

        }
    }
}
#pragma warning restore 1591
