#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Empleador;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Empleador/Index.cshtml")]
    public partial class _Views_Empleador_Index_cshtml : System.Web.Mvc.WebViewPage<Core.Empleador.Empleador>
    {
        public _Views_Empleador_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Empleador\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("<!-- Scripts-->\r\n<script");

WriteLiteral(" src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.13.0.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.5.0/angular-locale_es" +
"-es.min.js\"");

WriteLiteral("></script>\r\n\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 402), Tuple.Create("\"", 448)
, Tuple.Create(Tuple.Create("", 408), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts")
, 408), false)
, Tuple.Create(Tuple.Create(" ", 417), Tuple.Create("propios/empleadorController.js", 418), true)
);

WriteLiteral("></script>\r\n\r\n\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 470), Tuple.Create("\"", 496)
, Tuple.Create(Tuple.Create("", 477), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MyCss.css")
, 477), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n\r\n<div");

WriteLiteral(" ng-app=\"app\"");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" ng-controller=\"EmpleadorController\"");

WriteLiteral(" data-ng-init=\"obtenerDatosEmpleador()\"");

WriteLiteral(" class=\"row profile\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"profile-sidebar\"");

WriteLiteral(">\r\n                <!-- SIDEBAR USERPIC -->\r\n                <div");

WriteLiteral(" class=\"profile-userpic\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" data-ng-src=\"data:image/jpg;base64,{{empLoad.ImagenB64}}\"");

WriteLiteral(" data-err-src=\"images/png/avatar.png\"");

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(" />\r\n                </div>\r\n                <!-- END SIDEBAR USERPIC -->\r\n      " +
"          <!-- SIDEBAR USER TITLE -->\r\n                <div");

WriteLiteral(" class=\"profile-usertitle\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"profile-usertitle-name\"");

WriteLiteral(">\r\n                        {{empLoad.Nombre}} {{empLoad.Apellido1}}\r\n            " +
"        </div>\r\n                    <div");

WriteLiteral(" class=\"profile-usertitle-job\"");

WriteLiteral(">\r\n                        Empleador\r\n                    </div>\r\n               " +
" </div>\r\n                <!-- END SIDEBAR USER TITLE -->\r\n                <!-- S" +
"IDEBAR BUTTONS -->\r\n                <div");

WriteLiteral(" class=\"profile-userbuttons\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

WriteLiteral(">Cerrar Sesión</button>\r\n                </div>\r\n                <!-- END SIDEBAR" +
" BUTTONS -->\r\n                <!-- SIDEBAR MENU -->\r\n                <div");

WriteLiteral(" class=\"profile-usermenu\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" ng-class=\"{\'active\' : section==1}\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" ng-click=\"mostrarMiPerfil()\"");

WriteLiteral(" ng-init=\"section = 1\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\" glyphicon glyphicon-home\"");

WriteLiteral(">\r\n                                </i>\r\n                                Mis Dato" +
"s Personales\r\n                            </a>\r\n                        </li>\r\n " +
"                       <li");

WriteLiteral(" ng-class=\"{\'active\' : bussiness==1}\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" ng-click=\"mostrarEmpresa()\"");

WriteLiteral(" ng-init=\"bussiness = 0\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\" glyphicon glyphicon-user\"");

WriteLiteral(">\r\n                                </i>\r\n                                Mi Perfi" +
"l\r\n                            </a>\r\n                        </li>\r\n            " +
"            <li");

WriteLiteral(" ng-class=\"{\'active\' : ofertas==1}\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" ng-click=\"mostrarOfertas()\"");

WriteLiteral(" ng-init=\"ofertas = 0\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\" glyphicon glyphicon-ok\"");

WriteLiteral(@">
                                </i>
                                Mis Ofertas
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- END MENU -->
            </div>
        </div>
        <div");

WriteLiteral(" class=\"col-md-9\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"profile-content\"");

WriteLiteral(" name=\"section\"");

WriteLiteral(" ng-show=\"section==1\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Nombre: {{empLoad.Nombre}}</label><br />\r\n                <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Apellidos: {{empLoad.Apellido1}} {{empLoad.Apellido2}}</label><br />\r\n          " +
"  </div>\r\n            <div");

WriteLiteral(" class=\"bussiness-content\"");

WriteLiteral(" name=\"bussiness\"");

WriteLiteral(" ng-show=\"bussiness==1\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Nombre de Empresa: {{empLoad.NombreEmpresa}} </label><br />\r\n                <la" +
"bel");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Direccion: {{empLoad.Direccion}} </label><br />\r\n                <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Teléfono: {{empLoad.Telefono}} </label><br />\r\n                <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Email: {{empLoad.Email}} </label><br />\r\n                <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Tipo de industria: {{empLoad.TipoIndustriaNombre}} </label><br />\r\n             " +
"   <label");

WriteLiteral(" class=\"labelLetter\"");

WriteLiteral(">Número de empleados: {{empLoad.NumeroEmpleados}} </label><br />\r\n            </d" +
"iv>\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" name=\"ofertas\"");

WriteLiteral(" ng-show=\"ofertas==1\"");

WriteLiteral(">\r\n                <!-- Button trigger modal -->\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#modalPage\"");

WriteLiteral(">\r\n                    Nueva Oferta\r\n                </button>\r\n                <" +
"table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(@">
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Nº Vacantes</th>
                            <th>Fecha Inicio</th>
                            <th>Fecha Fin</th>
                            <th>Ver Oferta</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr");

WriteLiteral(" ng-repeat=\"oferta in listOfertas\"");

WriteLiteral(">\r\n                            <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">{{oferta.Titulo}}</td>\r\n                            <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">{{oferta.NumeroVacantes}}</td>\r\n                            <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">{{oferta.FechaLanzamientoS}}</td>\r\n                            <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">{{oferta.FechaFinS}}</td>\r\n                            <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#modalPageOferta\"");

WriteLiteral(" ng-click=\"verOferta(oferta)\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-eye-open\"");

WriteLiteral("></span></button>\r\n                            </td>\r\n                        </t" +
"r>\r\n                    </tbody>\r\n                </table>\r\n                <!--" +
" MODAL VER OFERTA -->\r\n                <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalPageOferta\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"exampleModalCenterTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"modal-dialog modal-dialog-centered\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"width: 55em;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"modal-header plus\"");

WriteLiteral(">\r\n                                <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"exampleModalLongTitle\"");

WriteLiteral(" style=\"font-size: 18px;\"");

WriteLiteral(">{{ofer.Titulo}}</h5>\r\n                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close ver\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\r\n                                </button>\r\n                     " +
"       </div>\r\n\r\n                            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                            <b>Título:</b><br />\r\n            " +
"                                <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"tituloL\"");

WriteLiteral(" id=\"tituloL\"");

WriteLiteral(">{{ofer.Titulo}}</label>\r\n                                        </div>\r\n\r\n     " +
"                                   <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                            <b>Fecha Fin:</b> <br />\r\n        " +
"                                    <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"fechafinL\"");

WriteLiteral(" id=\"fechafinL\"");

WriteLiteral(" />{{ofer.FechaFinS}}</label>\r\n                                        </div>\r\n\r\n" +
"                                        <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                            <b>Observaciones:</b><br />\r\n     " +
"                                       <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"observL\"");

WriteLiteral(" id=\"observL\"");

WriteLiteral(" />{{ofer.Observaciones}}</label>\r\n                                        </div>" +
"\r\n\r\n                                        <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                                    <b>Nº vacantes:</b><br />\r" +
"\n                                                    <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"vacantesL\"");

WriteLiteral(" id=\"vacantesL\"");

WriteLiteral(" />{{ofer.NumeroVacantes}}</label>\r\n                                             " +
"   </div>\r\n                                                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                                    <b>Sueldo:</b><br />\r\n    " +
"                                                <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"precioL\"");

WriteLiteral(" id=\"precioL\"");

WriteLiteral(@" />{{ofer.Sueldo}}</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                            <b>Descripción:</b><br />\r\n       " +
"                                     <label");

WriteLiteral(" class=\"labelOferta\"");

WriteLiteral(" name=\"descripL\"");

WriteLiteral(" id=\"descripL\"");

WriteLiteral(">{{ofer.Descripcion}}</label>\r\n                                        </div>\r\n  " +
"                                  </div>\r\n                                </div>" +
"\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"modal-footer form-group\"");

WriteLiteral(">\r\n                                <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(@">
                                    <thead>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Apellidos</th>
                                            <th>Teléfono</th>
                                            <th>Estudios</th>
                                            <th>Exp.Laboral</th>
                                            <th>CV</th>
                                            <th>Aceptar</th>
                                            <th>Rechazar</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr");

WriteLiteral(" ng-repeat=\"usu in listDemandantesInscritos\"");

WriteLiteral(">\r\n                                            <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">{{usu.NombreUsuario}}</td>\r\n                                            <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">{{usu.Apellido1}} {{usu.Apellido2}}</td>\r\n                                      " +
"      <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">{{usu.Telefono}}</td>\r\n                                            <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">{{usu.Nombre}}</td>\r\n                                            <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">{{usu.ExperienciaLAboral}}</td>\r\n                                            <td" +
"");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" href=\"{{usu.CV}}\"");

WriteLiteral(" download=\"CV\"");

WriteLiteral(">\r\n                                                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" ng-click=\"verOferta(oferta)\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-file\"");

WriteLiteral("></span></button>\r\n                                                </a>\r\n        " +
"                                    </td>\r\n                                     " +
"       <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" ng-click=\"cambiarEstado(usu, 1)\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></span></button></td>\r\n                                            <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" ng-click=\"cambiarEstado(usu, 2)\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"glyphicon glyphicon-remove\"");

WriteLiteral(@"></span></button></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- FIN VER OFERTA -->
            </div>
        </div>
        <!-- MODAL AÑADIR OFERTAS -->
        <!-- Modal  -->
        <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalPage\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"exampleModalCenterTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog modal-dialog-centered\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                        <h5");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"exampleModalLongTitle\"");

WriteLiteral(" style=\"font-size: 18px;\"");

WriteLiteral(">Añadir Oferta</h5>\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span>\r\n                        </button>\r\n                    </div>\r\n " +
"                   <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                    <b>Título:</b><br />\r\n                    " +
"                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"ofer.Titulo\"");

WriteLiteral(" class=\"form-control nOferta\"");

WriteLiteral(" name=\"titulo\"");

WriteLiteral(" id=\"titulo\"");

WriteLiteral(" required>\r\n                                </div>\r\n\r\n                           " +
"     <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                    <b>Fecha Fin:</b> <br />\r\n                " +
"                    <input");

WriteLiteral(" type=\"date\"");

WriteLiteral(" ng-model=\"ofer.FechaFin\"");

WriteLiteral(" class=\"form-control nOferta\"");

WriteLiteral(" name=\"fechafin\"");

WriteLiteral(" id=\"fechafin\"");

WriteLiteral(" />\r\n                                </div>\r\n\r\n                                <d" +
"iv");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                    <b>Observaciones:</b><br />\r\n             " +
"                       <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"ofer.Observaciones\"");

WriteLiteral(" class=\"form-control nOferta\"");

WriteLiteral(" name=\"observ\"");

WriteLiteral(" id=\"observ\"");

WriteLiteral(" required />\r\n                                </div>\r\n\r\n                         " +
"       <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                            <b>Nº vacantes:</b><br />\r\n       " +
"                                     <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" ng-model=\"ofer.NumeroVacantes\"");

WriteLiteral(" class=\"form-control nOferta medio\"");

WriteLiteral(" name=\"vacantes\"");

WriteLiteral(" id=\"vacantes\"");

WriteLiteral(" />\r\n                                        </div>\r\n                            " +
"            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                            <b>Sueldo:</b><br />\r\n            " +
"                                <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" ng-model=\"ofer.Sueldo\"");

WriteLiteral(" class=\"form-control nOferta medio\"");

WriteLiteral(" name=\"precio\"");

WriteLiteral(" id=\"precio\"");

WriteLiteral(" />\r\n                                        </div>\r\n                            " +
"        </div>\r\n                                </div>\r\n                        " +
"    </div>\r\n                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group plus\"");

WriteLiteral(">\r\n                                    <b>Descripción:</b><br />\r\n               " +
"                     <textarea");

WriteLiteral(" class=\"form-control tarea\"");

WriteLiteral(" rows=\"1\"");

WriteLiteral(" ng-model=\"ofer.Descripcion\"");

WriteLiteral(" name=\"descrip\"");

WriteLiteral(" id=\"descrip\"");

WriteLiteral(" required></textarea>\r\n                                </div>\r\n                  " +
"          </div>\r\n                        </div>\r\n                    </div>\r\n  " +
"                  <div");

WriteLiteral(" class=\"modal-footer form-group\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger btn-sm add\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cerrar</button>\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" ng-click=\"crearOferta()\"");

WriteLiteral(">Crear oferta</button>\r\n                    </div>\r\n                </div>\r\n     " +
"       </div>\r\n        </div>\r\n        ");

WriteLiteral("   \r\n    </div>\r\n</div>\r\n<br>\r\n<br>");

        }
    }
}
#pragma warning restore 1591
